flag_dict :
  train_model         : True
  optimize_bayes      : False
  plot_m_mppivert     : True
  plot_mppi_mdpi      : True
  plot_mppi_mdpi_fine : True
  plot_presel_eff     : True
  root_plots          : True

data_path           : '../data/'
analysis_name       : 'NEW_trees'
MC_signal_filename  : 'SignalTable_pp13TeV_mtexp.root'
background_filename : 'DataTable_pp_LS.root'
data_filename       : 'DataTable_pp.root'

presel_dict :
  MC_presel           : 'rej_accept > 0 and pt > 1.5'
  background_presel   : 'centrality < 0.17 and pt > 1.5'
  data_presel         : 'centrality < 0.17 and pt > 1.5'
  bckg_presel_vars    : ['ct', 'pt']
  data_presel_vars    : ['ct', 'pt']

eff_array  : [0.3,0.9,0.01]       #min, max, step