train_model      : False
optimize_bayes   : False
print_m_mppivert : True
print_mppi_mdpi  : True

data_path           : '../data/'
analysis_name       : 'NEW_trees'
MC_signal_filename  : 'SignalTable_pp13TeV_mtexp.root'
background_filename : 'DataTable_pp_LS.root'
data_filename       : 'DataTable_pp.root'