train_model      : False
optimize_bayes   : False
plot_m_mppivert  : True
plot_mppi_mdpi   : True

data_path           : '../data/'
analysis_name       : 'OLD_trees_with_cut'
MC_signal_filename  : 'SignalTable_pp13TeV_mtexp.root'
background_filename : 'DataTable_pp_LS_OLD.root'
data_filename       : 'DataTable_pp_OLD.root'