flag_dict :
  train_model         : True
  optimize_bayes      : False
  plot_m_mppivert     : True
  plot_mppi_mdpi      : True
  plot_mppi_mdpi_fine : True
  plot_presel_eff     : True
  plot_scatter        : True
  root_plots          : True

data_path           : '../data/'
analysis_name       : 'ROT_LS_17_05'
MC_signal_filename  : 'SignalTable_pp_mtexp.root'
background_filename : 'DataTable_pp_LS_rot.root'
data_filename       : 'DataTable_pp_data.root'

presel_dict :
  MC_presel           : 'rej_accept > 0 and pt > 1.5'
  background_presel   : 'centrality < 1. and pt > 1.5'
  data_presel         : 'centrality < 1. and pt > 1.5'
  bckg_presel_vars    : ['ct', 'pt']
  data_presel_vars    : ['ct', 'pt']

eff_array  : [0.5,0.9,0.01]       #min, max, step
train_vars : ["ct", "cos_pa" , "tpc_ncls_de" , "tpc_ncls_pr" , "tpc_ncls_pi", "tpc_nsig_de", "tpc_nsig_pr",
                  "tpc_nsig_pi", "dca_de_pr", "dca_de_pi", "dca_pr_pi", "dca_de_sv", "dca_pr_sv", "dca_pi_sv", "chi2"]